//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CDSBusinessEntities : DbContext
    {
        public CDSBusinessEntities()
            : base("name=CDSBusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Payment_Gateway> tbl_Payment_Gateway { get; set; }
        public virtual DbSet<tbl_Payment_History> tbl_Payment_History { get; set; }
        public virtual DbSet<tbl_Payment_Method> tbl_Payment_Method { get; set; }
        public virtual DbSet<tbl_Payment_Request_Response> tbl_Payment_Request_Response { get; set; }
        public virtual DbSet<tbl_Payment_Request_System> tbl_Payment_Request_System { get; set; }
        public virtual DbSet<tbl_Payment_Status_Master> tbl_Payment_Status_Master { get; set; }
        public virtual DbSet<tblMeruPayment> tblMeruPayments { get; set; }
        public virtual DbSet<tbl_PaymentTransaction> tbl_PaymentTransaction { get; set; }
        public virtual DbSet<tbl_Payment_Customer_Details> tbl_Payment_Customer_Details { get; set; }
        public virtual DbSet<tbl_Payment_Customer_Card_Details> tbl_Payment_Customer_Card_Details { get; set; }
        public virtual DbSet<tblTripReceiptCalculator> tblTripReceiptCalculators { get; set; }
        public virtual DbSet<tblJobBooking> tblJobBookings { get; set; }
        public virtual DbSet<tblKerbTripsCustomersData> tblKerbTripsCustomersDatas { get; set; }
        public virtual DbSet<tblTripMaster> tblTripMasters { get; set; }
        public virtual DbSet<tbl_Payment_Link> tbl_Payment_Link { get; set; }
        public virtual DbSet<Tbl_Payment_BlackListedCards> Tbl_Payment_BlackListedCards { get; set; }
        public virtual DbSet<tblCabMaster> tblCabMaster { get; set; }
    
        public virtual ObjectResult<Nullable<int>> USP_UpdatePostPaymentSuccess(string meruPaymentId, Nullable<int> amount, Nullable<int> paymentMethod, Nullable<int> paymentSource, string paymentId, string action, string additionalDetails)
        {
            var meruPaymentIdParameter = meruPaymentId != null ?
                new ObjectParameter("MeruPaymentId", meruPaymentId) :
                new ObjectParameter("MeruPaymentId", typeof(string));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(int));
    
            var paymentMethodParameter = paymentMethod.HasValue ?
                new ObjectParameter("PaymentMethod", paymentMethod) :
                new ObjectParameter("PaymentMethod", typeof(int));
    
            var paymentSourceParameter = paymentSource.HasValue ?
                new ObjectParameter("PaymentSource", paymentSource) :
                new ObjectParameter("PaymentSource", typeof(int));
    
            var paymentIdParameter = paymentId != null ?
                new ObjectParameter("PaymentId", paymentId) :
                new ObjectParameter("PaymentId", typeof(string));
    
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var additionalDetailsParameter = additionalDetails != null ?
                new ObjectParameter("AdditionalDetails", additionalDetails) :
                new ObjectParameter("AdditionalDetails", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_UpdatePostPaymentSuccess", meruPaymentIdParameter, amountParameter, paymentMethodParameter, paymentSourceParameter, paymentIdParameter, actionParameter, additionalDetailsParameter);
        }
    
        public virtual ObjectResult<usp_Wallet_GetPartialAmountTransactionDetails_Result> usp_Wallet_GetPartialAmountTransactionDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Wallet_GetPartialAmountTransactionDetails_Result>("usp_Wallet_GetPartialAmountTransactionDetails");
        }
    }
}
