//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_Request_System
    {
        public short Payment_Request_System_ID { get; set; }
        public string Payment_Request_System { get; set; }
        public string Payment_Request_System_Secret { get; set; }
        public System.DateTime Record_Created_DateTime { get; set; }
        public System.DateTime Record_Updated_DateTime { get; set; }
        public string Record_Status { get; set; }
        public string Payment_Request_System_Name { get; set; }
        public string Payment_Request_System_KeyInput { get; set; }
        public string Payment_Request_System_Return_URL { get; set; }
        public string ColorCode { get; set; }
        public string Payment_Request_Channel_Code { get; set; }
        public string QueueName { get; set; }
        public Nullable<bool> EnableAuthToken { get; set; }
        public string SPName { get; set; }
    }
}
