//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_Customer_Card_Details
    {
        public int ID { get; set; }
        public string Name_On_Card { get; set; }
        public string Network_Name { get; set; }
        public string Last_Four_Digit { get; set; }
        public string Token_ID { get; set; }
        public string Provider_Customer_ID { get; set; }
        public Nullable<bool> Is_Default { get; set; }
        public string Card_Type { get; set; }
        public string Card_Issuer_Code { get; set; }
        public Nullable<short> Card_Status { get; set; }
        public Nullable<System.DateTime> Record_Created_DateTime { get; set; }
        public Nullable<System.DateTime> Record_Update_DateTime { get; set; }
        public Nullable<System.DateTime> Card_Exipry_DateTime { get; set; }
        public bool IsDeleted { get; set; }
        public string DeviceId { get; set; }
    }
}
