//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_History
    {
        public long Payment_Request_ID { get; set; }
        public string Payment_Status_Code { get; set; }
        public System.DateTime Record_Created_DateTime { get; set; }
        public string Updating_Process { get; set; }
        public int Payment_Status_ID { get; set; }
        public string PaymentTransactionId { get; set; }
    }
}
