//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Payment_BlackListedCards
    {
        public int BlackListedCardId { get; set; }
        public string IssuerCode { get; set; }
        public string NetworkName { get; set; }
        public string CardType { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
