//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_Request_Response
    {
        public long Payment_Request_Response_ID { get; set; }
        public int PaymentIncrementId { get; set; }
        public string Request_Key { get; set; }
        public string Request_Value { get; set; }
        public string Record_Call_Source { get; set; }
        public string Record_Type { get; set; }
        public System.DateTime Record_Created_DateTime { get; set; }
    }
}
