//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_Link
    {
        public string Payment_Transaction_ID { get; set; }
        public string Request_RefId { get; set; }
        public long Payment_Amount_Paise { get; set; }
        public string PG_OrderId { get; set; }
        public string PG_PaymentId { get; set; }
        public string PG_InvoiceId { get; set; }
        public string PG_ReceiptNo { get; set; }
        public string PG_Ref_Data { get; set; }
        public Nullable<int> Payment_Source { get; set; }
        public Nullable<int> Payment_Method { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public long PaymentLink_Id { get; set; }
    }
}
