//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_Customer_Details
    {
        public int ID { get; set; }
        public string Provider_Customer_ID { get; set; }
        public Nullable<int> Payment_Gateway_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Email { get; set; }
        public string Customer_Mobile_No { get; set; }
        public Nullable<System.DateTime> Record_Created_DateTime { get; set; }
        public Nullable<System.DateTime> Record_Update_DateTime { get; set; }
        public Nullable<int> Customer_Status { get; set; }
    }
}
