//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentTransaction
    {
        public long PaymentIncrementId { get; set; }
        public string Payment_Transaction_ID { get; set; }
        public string RequestSource { get; set; }
        public string RequestRefValues { get; set; }
        public long Payment_Amount_Paise { get; set; }
        public int PaymentSource { get; set; }
        public int PaymentMethod { get; set; }
        public int PaymentStatus { get; set; }
        public string PaymentRefValues { get; set; }
        public string PaymentRefData1 { get; set; }
        public string PaymentRefData2 { get; set; }
        public string PaymentRefData3 { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string Payment_Gateway_Code { get; set; }
        public string Payment_Method_Code { get; set; }
        public string Payment_Status_Code { get; set; }
        public string PG_Transaction_Code { get; set; }
        public string RequestRefId { get; set; }
        public long Refund_Amount_Paise { get; set; }
        public string PurchaseDescription { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public bool Payment_Reconciled { get; set; }
        public string Payment_Type { get; set; }
        public string DeviceId { get; set; }
        public Nullable<int> PaymentMethodRefId { get; set; }
        public int BusinessCategoryId { get; set; }
        public Nullable<System.DateTime> LastStatusOn { get; set; }
        public string PaymentResponse { get; set; }
        public Nullable<long> AmountPaid { get; set; }
        public Nullable<long> AmountDue { get; set; }
        public string Currency { get; set; }
        public string Receipt { get; set; }
        public string Offer_Id { get; set; }
        public string Notes { get; set; }
        public string OrderResponse { get; set; }
    }
}
