//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment_Status_Master
    {
        public short Payment_Status_ID { get; set; }
        public string Payment_Status { get; set; }
        public string Payment_Status_Desc { get; set; }
        public System.DateTime Record_Created_DateTime { get; set; }
        public System.DateTime Record_Updated_DateTime { get; set; }
        public string Record_Status { get; set; }
        public string Payment_Status_Code { get; set; }
    }
}
