//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCabMaster
    {
        public int CabID { get; set; }
        public Nullable<short> CabTypeID { get; set; }
        public string CabRegistrationNo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string EngineNo { get; set; }
        public string ChasisNo { get; set; }
        public string CabYearMake { get; set; }
        public Nullable<byte> SpeedLimit { get; set; }
        public string OdoMeterNo { get; set; }
        public short CityID { get; set; }
        public string CabModelName { get; set; }
        public string CabCompanyName { get; set; }
        public string CabDesc { get; set; }
        public byte CabStatusID { get; set; }
        public string SeibelCabID { get; set; }
        public Nullable<float> CabLatitude { get; set; }
        public Nullable<float> CabLongitude { get; set; }
        public Nullable<byte> MeterStatus { get; set; }
        public Nullable<bool> IgnitionStatus { get; set; }
        public string CabGPSDateTime { get; set; }
        public Nullable<byte> Speed { get; set; }
        public Nullable<short> Direction { get; set; }
        public string CabLocation { get; set; }
        public string RecordUpdateTime { get; set; }
        public Nullable<double> OdoMeterReading { get; set; }
        public Nullable<int> OdometerUpdateUserID { get; set; }
        public Nullable<double> PreviousOdometer { get; set; }
        public System.DateTime OdometerUpdateTime { get; set; }
        public Nullable<int> LocalityID { get; set; }
        public string LocalityName { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string ZoneName { get; set; }
        public Nullable<int> SubLocalityID { get; set; }
        public string GPSFixedLocation { get; set; }
        public Nullable<System.DateTime> GPSFixedTime { get; set; }
        public Nullable<float> GPSFixedLatitude { get; set; }
        public Nullable<float> GPSFixedLongitude { get; set; }
        public Nullable<System.DateTime> GPSFixedTimeForDispatch { get; set; }
        public string CabModel_Actual { get; set; }
        public Nullable<byte> BrandTypeID { get; set; }
        public Nullable<byte> ProductTypeID { get; set; }
        public string SPID { get; set; }
        public string CabColor { get; set; }
        public Nullable<byte> BusinessCategoryID { get; set; }
        public string Vehicle_Identification_No { get; set; }
        public string PermitType { get; set; }
        public string ActualCity { get; set; }
        public string ActualState { get; set; }
    }
}
