//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobBooking
    {
        public int JobID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobileNo { get; set; }
        public string CustomerContactFirsttName { get; set; }
        public string CustomerContactLastName { get; set; }
        public string CustomerContactMobileNo { get; set; }
        public byte JobTypeID { get; set; }
        public Nullable<int> TerminalID { get; set; }
        public System.DateTime PickUpTime { get; set; }
        public string CustomerPickUpAddress { get; set; }
        public string Preference { get; set; }
        public string Landmark { get; set; }
        public Nullable<int> PickUpAddressPointID { get; set; }
        public Nullable<int> PickUpLocalityID { get; set; }
        public Nullable<int> PickUpZoneID { get; set; }
        public string PickUpMessage { get; set; }
        public Nullable<byte> CabTypeID { get; set; }
        public string CabModelName { get; set; }
        public string DestinationAddress { get; set; }
        public Nullable<int> DestAddressPointID { get; set; }
        public Nullable<int> DestLocalityId { get; set; }
        public Nullable<int> DestZoneID { get; set; }
        public Nullable<byte> NoOfBags { get; set; }
        public Nullable<byte> NoOfCabs { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> CallStartTime { get; set; }
        public System.DateTime JobCreationTime { get; set; }
        public Nullable<System.DateTime> CabAssignedTime { get; set; }
        public Nullable<short> CallDuration { get; set; }
        public Nullable<byte> LanguageID { get; set; }
        public Nullable<System.DateTime> DropTime { get; set; }
        public short CityID { get; set; }
        public Nullable<int> AddFareID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MappingID { get; set; }
        public Nullable<byte> ChannelID { get; set; }
        public string SiebelJobID { get; set; }
        public Nullable<byte> CancelId { get; set; }
        public string CancelReason { get; set; }
        public string CabRegistrationNo { get; set; }
        public bool SmsStatus { get; set; }
        public Nullable<bool> SmsAlert { get; set; }
        public Nullable<short> RejectId { get; set; }
        public string RejectRemarks { get; set; }
        public string TagAs { get; set; }
        public Nullable<short> Quota { get; set; }
        public Nullable<short> TimetoDispatch { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<int> CancelledUserID { get; set; }
        public Nullable<short> ModifiedCallDuration { get; set; }
        public Nullable<short> CancelledCallDuration { get; set; }
        public Nullable<int> ManualDispatchedUser { get; set; }
        public Nullable<bool> CalledSubscriber { get; set; }
        public Nullable<bool> InformedCustomer { get; set; }
        public string IVRSChannelID { get; set; }
        public Nullable<int> JobSubscriberID { get; set; }
        public Nullable<bool> AirportJob { get; set; }
        public Nullable<bool> CorporateJob { get; set; }
        public Nullable<bool> MPC { get; set; }
        public string EmailAddress { get; set; }
        public string TrackMobile { get; set; }
        public Nullable<int> QuotaBorrowingZoneID { get; set; }
        public Nullable<byte> MobileSMSStatus { get; set; }
        public Nullable<byte> PromoSMSStatus { get; set; }
        public Nullable<int> CRDUserID { get; set; }
        public Nullable<byte> CRDCount { get; set; }
        public Nullable<short> DropCityID { get; set; }
        public Nullable<bool> ReturnTrip { get; set; }
        public string RetentionTime { get; set; }
        public Nullable<byte> StateTaxStatus { get; set; }
        public Nullable<byte> IsGenie { get; set; }
        public string PromoCode { get; set; }
        public Nullable<decimal> CouponAmount { get; set; }
        public Nullable<int> redeempoints { get; set; }
        public Nullable<decimal> RedeemAmount { get; set; }
        public string CabDeviceID { get; set; }
        public Nullable<float> PickupLat { get; set; }
        public Nullable<float> PickupLong { get; set; }
        public Nullable<byte> BrandTypeID { get; set; }
        public Nullable<System.DateTime> CabConfSMSSenttime { get; set; }
        public Nullable<float> DropLat { get; set; }
        public Nullable<float> DropLong { get; set; }
        public Nullable<byte> AssignedCabBrandTypeID { get; set; }
        public Nullable<byte> AssignedCabProductTypeID { get; set; }
        public Nullable<byte> IsRideShare { get; set; }
        public Nullable<bool> IsIxigoSent { get; set; }
        public Nullable<double> RatePerKM { get; set; }
        public Nullable<short> AirportNotifySatus { get; set; }
        public Nullable<int> WalletSMSStatus { get; set; }
        public string RiderName { get; set; }
        public Nullable<int> RefusedSMSStatus { get; set; }
        public Nullable<int> FixedFareLogId { get; set; }
        public Nullable<byte> ProductTypeId { get; set; }
        public Nullable<byte> BusinessCategoryID { get; set; }
        public Nullable<byte> IsTripStartSMSSent { get; set; }
        public Nullable<byte> IsTripEndSMSSent { get; set; }
        public Nullable<bool> IsInterCity { get; set; }
        public Nullable<bool> ISDriver_SMSSent_Outstation { get; set; }
        public Nullable<bool> IsAirportDrop { get; set; }
        public bool Driver_ReminderSMS1_Out { get; set; }
        public bool Driver_ReminderSMS2_Out { get; set; }
        public Nullable<bool> Outstation_DU_SMS_Alert { get; set; }
        public Nullable<int> STFStaus { get; set; }
        public string STFDeviceID { get; set; }
        public string STFCabNo { get; set; }
        public Nullable<System.DateTime> STFCabSentTime { get; set; }
    }
}
