//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKerbTripsCustomersData
    {
        public int KerbCustomerID { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string SiebelDeviceID { get; set; }
        public Nullable<System.DateTime> TripStartTime { get; set; }
        public string CabRegistrationNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CityID { get; set; }
        public int SMSStatus { get; set; }
        public Nullable<System.DateTime> EmailReceivedTime { get; set; }
        public Nullable<System.DateTime> RecordedDateTime { get; set; }
        public Nullable<int> WalletSMSStatus { get; set; }
        public Nullable<int> TripID { get; set; }
        public Nullable<bool> Feedback_SMS { get; set; }
        public Nullable<bool> Ebill_SMS { get; set; }
        public Nullable<float> DropLatitude { get; set; }
        public Nullable<float> DropLongitude { get; set; }
        public Nullable<double> FareMultiplier_Kerb { get; set; }
    }
}
