//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeruPaymentDAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMeruPayment
    {
        public int PaymentIncrementId { get; set; }
        public string RequestSource { get; set; }
        public string RequestRefValues { get; set; }
        public int PaymentAmount { get; set; }
        public string PaymentSource { get; set; }
        public string PaymentMethod { get; set; }
        public int PaymentStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string PaymentRefValues { get; set; }
        public string PaymentRefData1 { get; set; }
        public string PaymentRefData2 { get; set; }
        public string PaymentRefData3 { get; set; }
        public string PaymentDetail { get; set; }
        public Nullable<bool> Payment_Reconciled { get; set; }
    }
}
